language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t myownez/docker-react -f Dockerfile.dev .

script:
  - docker run myownez/docker-react npm run test -- --coverage